#---------------------------------#
#      general configuration      #
#---------------------------------#

# branches to build
branches:
  only:
    - master

#---------------------------------#
#    environment configuration    #
#---------------------------------#

os: Windows Server 2012

init:
  - git config --global core.autocrlf input

#environment variables
environment:
  install_builder_license_signature:
    secure: 3j/EJAZzA8i/OfWyhmvLnzk7SZ8/KNaaTVfWyw0uVhe5gcZfhlGVPfgwrdnvEut3
  gh_token:
    secure: K8R2b8g3A8zB4IFQ0/G/fU8IKhU3PoFaKZARKl0IbCUvVxfzzfVY9yKUVPjM4M4V
  FD_CERT_PWD:
    secure: LDV1CBXqfvvW0VpFmQX6Zbp7Eik6IJ4TxdDwaKgpTC+A9DAX/H2GRssOmqB+BWZj
  FLICKR_DOWNLOADR_SHARED_SECRET:
    secure: DNxghVZ3HphcDvLH6HNEAka2DwJOeMWP0sruloVZj3r4NmImm5pr2vkyN0vC/Bdn
  FLICKR_DOWNLOADR_CONSUMER_KEY:
    secure: iNNRAx5PYpkP9rOHhWrkiJIaOoqXpDgo1E7q46C6n64fhmOGWXKENpB+PYssnfoW16e4YWjvWGw/guh1bczb1Q9WQAniR1KmTt5KBd+0i+UU6ahE2k1xWNuI2E2tbCLD
  FLICKR_DOWNLOADR_CONSUMER_SECRET:
    secure: clxtbFASnQa9Z8px9an8QdKyrZghSZMFljjrtiH3QrBDUjb31ASYH0NcG723YPVeaGK4RRGtUDIYTboGroz8f53PZi9yom7dzC4bZ3WXv/o=

#---------------------------------#
#       build configuration       #
#---------------------------------#

build_script:
  - cd ./build-tools
  - go appveyor Release
  - echo 'Build (and Deploy) completed...'

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test: off

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:

  - path: dist
    name: dist
    type: zip

  - path: build-tools\*.log
    name: logs
    type: zip

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy: off

#---------------------------------#
#        global handlers          #
#---------------------------------#
